apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beacon-storage
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # <--- Modifica questa riga
  resources:
    requests:
      storage: 1Gi