apiVersion: v1
kind: Service
metadata:
  name: beacon-api
  namespace: sentinelgrid
  labels:
    app: beacon-api
spec:
  type: ClusterIP
  selector:
    app: beacon-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-api
  namespace: sentinelgrid
  labels:
    app: beacon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon-api
  template:
    metadata:
      labels:
        app: beacon-api
    spec:
      containers:
        - name: beacon-api
          # Placeholder da sostituire con l'IMAGE_URI generato dalla pipeline
          image: 889276611436.dkr.ecr.eu-west-1.amazonaws.com/beacon-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATA_FILE
              valueFrom:
                configMapKeyRef:
                  name: sentinelgrid-config
                  key: DATA_FILE
            - name: BEACON_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sentinelgrid-secrets
                  key: BEACON_API_KEY
          volumeMounts:
            - name: data-volume
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: beacon-api-pvc