apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelgrid-config
  namespace: sentinelgrid
  labels:
    app: sentinelgrid
data:
  DATA_FILE: "/data/incidents.jsonl"
  BEACON_API_URL: "http://beacon-api:8080"
  COMMAND_API_URL: "http://command-api:8080"