apiVersion: v1
kind: Secret
metadata:
  name: sentinelgrid-secrets
  namespace: sentinelgrid
  labels:
    app: sentinelgrid
type: Opaque
data:
  BEACON_API_KEY: YmVhY29uX2FwaV9rZXkK
  API_KEY: YXBpX2tleQo=