apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beacon-api-pvc
  namespace: sentinelgrid
  labels:
    app: beacon-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard