apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-api
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon-api
  template:
    metadata:
      labels:
        app: beacon-api
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: beacon-api
        image: 889276611436.dkr.ecr.eu-west-1.amazonaws.com/beacon-api:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DATA_FILE
          value: "/data/incidents.jsonl"
        envFrom:
        - secretRef:
            name: sentinel-secret
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: beacon-storage