apiVersion: batch/v1
kind: CronJob
metadata:
  name: triage-worker
  namespace: prod
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ecr-secret
          containers:
          - name: triage-worker
            image: IMAGE_PLACEHOLDER_TRIAGE
            envFrom:
            - configMapRef:
                name: sentinel-config
            - secretRef:
                name: sentinel-secret
          restartPolicy: OnFailure